name: custom-workflow
run-name: ${{ github.actor }} is testing out Github actions
'on': push
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: This is name in steps
        run: echo "This is customized workflow."
      - run: |
          echo "OS name: ${{ runner.os }}"
      - run: |
          echo "Github branch: ${{ github.ref }}"
      - run: |
          echo "Github repository: ${{ github.repository }}"
      - run: |
          echo "Github workspace: ${{ github.workspace }}"
      - run: |
          echo "Github actor: ${{ github.actor }}"
      - run: |
          echo "Job status: ${{ job.status }}"
      - run: |
          echo "Github event name: ${{ github.event_name }}"
